name: "Check prelude"

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-flakes:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: pre-commit-hooks
      - run: rm -rf /opt&

      - name: Check flake
        working-directory: ./
        run: nix flake check -L --show-trace --no-write-lock-file
